#Define deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-scaling-deployment
  labels:
    app: sbservice-scaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbservice-scaling
  template:
    metadata:
      labels:
        app: sbservice-scaling
    spec:
      containers:
      - name: sbservice-scaling
        image: goyalsweta/sbservice-scaling:3.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
