#Define service

apiVersion: v1
kind: Service
metadata:
  name: scaling-service
spec:
  type: NodePort
  selector:
    app: sbservice-scaling
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30015

